//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesMoviesProjectver3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Games
    {
        public int ID { get; set; }
        public string Gamename { get; set; }
        public string Director { get; set; }
        public string Technology { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Image { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
    }
}
